module.exports = [
  `ALTER TABLE devices ADD COLUMN IF NOT EXISTS os_guess_source VARCHAR(32);`,
  `ALTER TABLE devices ADD COLUMN IF NOT EXISTS os_guess_confidence DOUBLE PRECISION;`,
  `ALTER TABLE devices ADD COLUMN IF NOT EXISTS os_detections JSONB NOT NULL DEFAULT '[]'::jsonb;`,
  `ALTER TABLE devices ADD COLUMN IF NOT EXISTS script_results JSONB NOT NULL DEFAULT '{}'::jsonb;`,
  `ALTER TABLE devices ADD COLUMN IF NOT EXISTS metadata JSONB NOT NULL DEFAULT '{}'::jsonb;`,
  `UPDATE devices SET os_detections = '[]'::jsonb WHERE os_detections IS NULL;`,
  `UPDATE devices SET script_results = '{}'::jsonb WHERE script_results IS NULL;`,
  `UPDATE devices SET metadata = '{}'::jsonb WHERE metadata IS NULL;`,
  `ALTER TABLE ports ADD COLUMN IF NOT EXISTS metadata JSONB NOT NULL DEFAULT '{}'::jsonb;`,
  `ALTER TABLE ports ADD COLUMN IF NOT EXISTS script_results JSONB NOT NULL DEFAULT '{}'::jsonb;`,
  `ALTER TABLE ports ADD COLUMN IF NOT EXISTS last_source VARCHAR(32);`,
  `ALTER TABLE ports ADD COLUMN IF NOT EXISTS source_confidence DOUBLE PRECISION NOT NULL DEFAULT 0;`,
  `UPDATE ports SET metadata = '{}'::jsonb WHERE metadata IS NULL;`,
  `UPDATE ports SET script_results = '{}'::jsonb WHERE script_results IS NULL;`,
  `UPDATE ports SET source_confidence = 0 WHERE source_confidence IS NULL;`,
  `ALTER TABLE vulnerabilities ADD COLUMN IF NOT EXISTS cve_list TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];`,
  `ALTER TABLE vulnerabilities ADD COLUMN IF NOT EXISTS nvt_oid TEXT;`,
  `UPDATE vulnerabilities SET cve_list = ARRAY[cve] WHERE cve IS NOT NULL AND (cve_list IS NULL OR array_length(cve_list, 1) IS NULL);`,
  `UPDATE vulnerabilities SET cve_list = ARRAY[]::TEXT[] WHERE cve_list IS NULL;`,
  `CREATE INDEX IF NOT EXISTS idx_vulnerabilities_cve_list ON vulnerabilities USING GIN (cve_list);`,
  `
    CREATE TABLE IF NOT EXISTS tls_certificates (
      id SERIAL PRIMARY KEY,
      device_id INTEGER NOT NULL REFERENCES devices(id) ON DELETE CASCADE,
      asset_hash TEXT NOT NULL,
      port INTEGER,
      protocol VARCHAR(16),
      subject TEXT,
      issuer TEXT,
      serial_number TEXT,
      fingerprint_sha256 TEXT,
      not_before TIMESTAMPTZ,
      not_after TIMESTAMPTZ,
      raw_text TEXT,
      metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
      source VARCHAR(32) NOT NULL DEFAULT 'greenbone',
      first_seen TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      last_seen TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      CONSTRAINT tls_certificates_device_hash_unique UNIQUE (device_id, asset_hash)
    );
  `,
  `
    CREATE TABLE IF NOT EXISTS ssh_host_keys (
      id SERIAL PRIMARY KEY,
      device_id INTEGER NOT NULL REFERENCES devices(id) ON DELETE CASCADE,
      asset_hash TEXT NOT NULL,
      port INTEGER,
      protocol VARCHAR(16),
      key_type TEXT,
      fingerprint TEXT,
      key_bits INTEGER,
      raw_text TEXT,
      metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
      source VARCHAR(32) NOT NULL DEFAULT 'greenbone',
      first_seen TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      last_seen TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      CONSTRAINT ssh_host_keys_device_hash_unique UNIQUE (device_id, asset_hash)
    );
  `,
  `CREATE INDEX IF NOT EXISTS idx_tls_certificates_device ON tls_certificates(device_id);`,
  `CREATE INDEX IF NOT EXISTS idx_tls_certificates_port ON tls_certificates(port);`,
  `CREATE INDEX IF NOT EXISTS idx_ssh_host_keys_device ON ssh_host_keys(device_id);`,
  `CREATE INDEX IF NOT EXISTS idx_ssh_host_keys_port ON ssh_host_keys(port);`,
];
